### ISSUE TITLE
Access to server

### ISSUE THREAD

**Issue by aserhany** [Rostlab/DM_CS_WS_2016-17#5] opened 2016-11-12 22:33 UTC
@juanmirocks 
Hi Juan, we were able to successfully connect to the server via ssh. Unfortunately, we weren't able to use certain program like MySQL server. Would it possible to give us the respective access rights?
Furthermore, we would like to use Rapidminer but couldn't find or install it. Would it be possible to provide it to us?
Thank you in advance.

**Comment by juanmirocks** [comment] 2016-11-13 17:43
Thanks @aserhany 

Tim our administrator (@T1mK) or Lothar (@lrrichter) can provide a better solution to this -- Any ideas guys?

**Comment by T1mK** [comment] 2016-11-14 10:18
What server are  you trying to connect to? What database do you need on mysql? How much space will your database use? Who are 'we'? Please coordinate with Juanmi or Lothar,  and me, via e-mail over the details of the account(s) and database(s) for which you need. Thanks. @aserhany

**Comment by juanmirocks** [comment] 2016-11-14 10:25
Thanks @T1mK 

more info:
- they (their 'we') are a group of 3-4 people of the Data Mining course.
- They are accessing the students servers
- I guess they just wanna store their data on a sql db. This access to mysql should be available to all DM students, I guess. 
- @aserhany please clarify how much space you need

**Comment by aserhany** [comment] 2016-11-14 13:03
@T1mK @juanmirocks 
As Juan mentioned, our team (@ssoima, @chaoran-chen, and I) need 50GB space in the beginning. Later after joining the different datasets and forming the single table (as required at the Course) we will definitely need less space. Regarding your questions:
- Our accounts on the student servers: cchen, ssoima, aabdelrahman
- We need mysql to store our datasets 
- We also need "rapidminer", which we currently can't install ourselves on the servers. 

Please let us know if you need further information from our side, thanks.

**Comment by lrrichter** [comment] 2016-11-16 12:05
Please find Rapidminer in /opt/rapidminer-studio. On the other issues we work.

Best, Lothar

**Comment by T1mK** [comment] 2016-11-16 14:03
Hi All,

> Ouraccounts on the student servers: cchen, ssoima, aabdelrahman
> We need mysql to store our datasets
> The accounts mentioned have access to dataminer.informatik.tu-muenchen.de http://dataminer.informatik.tu-muenchen.de/ via SSH on port 8574.

Once there, you can access MySQL using:

mysql -u <your username> -p

The password to each of your accounts is stored in your home directory in the file mysql_pass.txt

Your database name is ‘csa_group’.

Your temporary directory for storing data is '/var/tmp/csa_group’ on the dataminer machine.

As Lothar Richter mentioned, the RapidMiner installation is at ' /opt/rapidminer-studio’

Good luck and have fun!

Cheers,
Tim

**Comment by juanmirocks** [comment] 2016-11-16 15:58
Thank you a million @T1mK

**Comment by juanmirocks** [comment] 2016-11-16 15:58
@aserhany please consider closing this issue once everything is solved :)

**Comment by ssoima** [comment] 2016-11-17 14:27
@juanmirocks , @T1mK
Hi Juan & Tim, we have got the access to the database. However, making more demanding queries on the MySQL database does not work for us. The query at the end of my comment took 11 min on our computer in a PostgreSQL database, whereas on the server it run for more than 1 hour and eventually crashed. Do you have any idea how we could solve this problem?

Top dump of our mysql process, to help troubleshoot the bottleneck:
PID     USER     PR  NI    VIRT         RES    SHR    S  %CPU %MEM     TIME+         COMMAND
21517 mysql     20   0     11.834g    0.011t  7212   S  31.4      8.6          204:17.62    mysqld

insert into crimes_uk_crimes (
  crime_id,
  month,
  reported_by,
  falls_within,
  longitude,
  latitude,
  location,
  lsoa_code,
  lsoa_name,
  crime_type,
  last_outcome_category,
  suspect_identified,
  context,
  county,
  outcome_type,
  suspect_identified_outcome)
select
  s.crime_id,
  s.month,
  s.reported_by,
  s.falls_within,
  s.longitude,
  s.latitude,
  s.location,
  s.lsoa_code,
  s.lsoa_name,
  s.crime_type,
  s.last_outcome_category,
  s.suspect_identified,
  s.context,
  s.county,
  o.outcome_type,
  o.suspect_identified
from crimes_uk_streets s left outer join crimes_uk_outcomes o on s.crime_id = o.crime_id;

**Comment by juanmirocks** [comment] 2016-11-17 19:35
@T1mK do you have any ideas? **Thank you Tim**

**Comment by T1mK** [comment] 2016-11-18 10:45
Hi Guys,

Yeah, I have an answer for you.. it’s easy. The problem is that the mysql databases are running on an external USB 2.0 disk. That’s the problem! You see, we’re a little short on cash, so I had to hack something together. 

In the meantime, however, some compute nodes have failed, leaving behind some nice 500GB SAS disks which I can install for you to replace the external USB disk. So, what I’ll do today is shut down the mysql daemon and copy all the databases over to the 500GB SAS disks and then start it up again. Then I’ll let you know.

Sound good?

Cheers,
Tim

**Comment by juanmirocks** [comment] 2016-11-18 10:50
**mysql on a USBK 2.0 disk** both a 😱 and a 😎

**Comment by ssoima** [comment] 2016-11-18 11:21
Yeah, it's a great improvement :)).
Thank you!!

**Comment by T1mK** [comment] 2016-11-18 16:47
Howdy Y’all,

So, the new disks are installed, mirrored, and hosting all of the MySQL data. I rebooted the server, and you may now do what you need to do. I also doubled the amount of RAM available for the buffers. Overall, you should see some improvement.

Please let me know how it works out for you all.

Cheers,
Tim

**Comment by juanmirocks** [comment] 2016-11-20 08:25
@T1mK 🙏

@ssoima @aserhany If everything works now OK or at least acceptable, please close the issue.

**Comment by juanmirocks** [comment] 2016-12-10 18:37
@ssoima can you explain why you reopened this?

**Comment by ssoima** [comment] 2016-12-10 20:53
Hi @juanmirocks @T1mK ,
we were trying to run the RapidMiner on the server. However this did not work because we cannot use an Xsession. Also, using ssh -X did not work. 

Here the error:
`No X11 DISPLAY variable was set, but this program performed an operation which requires it.`

We also tried to use the RapidMiner-batch.sh and we got this error:
```
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.I18N <clinit>
INFO: Set locale to en.
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.PlatformUtilities logInfo
INFO: rapidminer.home is '/opt/rapidminer-studio'.
Dec 10, 2016 9:37:31 PM com.rapidminer.core.license.ProductConstraintManager initialize
INFO: Initializing license manager.
Dec 10, 2016 9:37:31 PM com.rapidminer.core.license.ProductConstraintManager initialize
INFO: Using default license location.
Dec 10, 2016 9:37:31 PM com.rapidminer.core.license.ProductConstraintManager initialize
INFO: Registering default product.
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Data Editor
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Productivity
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Cloud Connectivity
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Cloud Execution
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: JDBC Connectors
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Process Scheduling
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Operator Recommender
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Advanced File Connectors
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Remote Repository
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Social Media
Dec 10, 2016 9:37:31 PM com.rapidminer.tools.plugin.Plugin registerPlugins
INFO: Register plugin: Legacy Result Access
Dec 10, 2016 9:37:33 PM com.rapidminer.tools.config.ConfigurationManager register
INFO: Registered configurator Salesforce Connection.
Dec 10, 2016 9:37:33 PM com.rapidminer.tools.config.ConfigurationManager register
INFO: Registered configurator Amazon S3 Connection.
Dec 10, 2016 9:37:33 PM com.rapidminer.tools.config.ConfigurationManager register
INFO: Registered configurator Dropbox Connection.
Dec 10, 2016 9:37:34 PM com.rapidminer.extension.jdbc.tools.jdbc.JDBCProperties <init>
WARNING: Missing database driver class name for ODBC Bridge (e.g. Access)
Dec 10, 2016 9:37:34 PM com.rapidminer.extension.jdbc.tools.jdbc.JDBCProperties registerDrivers
INFO: JDBC driver ca.ingres.jdbc.IngresDriver not found. Probably the driver is not installed.
Dec 10, 2016 9:37:35 PM com.rapidminer.tools.config.ConfigurationManager register
INFO: Registered configurator Twitter Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Load configuration for Amazon S3 Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ClientConfigurationManager loadAllParameters
INFO: No configuration file found for Amazon S3 Connection
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Loaded configurations for 0 objects of type Amazon S3 Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Load configuration for Dropbox Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ClientConfigurationManager loadAllParameters
INFO: No configuration file found for Dropbox Connection
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Loaded configurations for 0 objects of type Dropbox Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Load configuration for Salesforce Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ClientConfigurationManager loadAllParameters
INFO: No configuration file found for Salesforce Connection
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Loaded configurations for 0 objects of type Salesforce Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Load configuration for Twitter Connection.
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ClientConfigurationManager loadAllParameters
INFO: No configuration file found for Twitter Connection
Dec 10, 2016 9:37:47 PM com.rapidminer.tools.config.ConfigurationManager loadConfiguration
INFO: Loaded configurations for 0 objects of type Twitter Connection.
Your license does not allow for using the CLI.
```

After researching about it, I think that the best solution would be to have the RapidMiner server instead of the RapidMiner-studio client [1]. Would this be possible?
Alternatively, if you were able to use it, it would be nice to show us how you used it.

We also wanted to share with you the fact that we switched to MonetDB, that is much faster then postgresql. Therefore, we taught that it would be cool if we could have that on the server so that all of us could use it. Maybe this also helps other teams.

[1] https://rapidminer.com/products/server/

**Comment by juanmirocks** [comment] 2016-12-12 07:13
Tim can give more info on the servers.

What other past students did was to first create the visual workflow of training on their local machines. Then, they saved the workflow into a file (I believe .xml format). And then, they run on the server rapidminer as a command-line program with the respective workflow file.

Hope that helps.

**Comment by T1mK** [comment] 2016-12-12 10:05
Hello,

> we were trying to run the RapidMiner on the server. However this did not work because we cannot use an Xsession. Also, using ssh -X did not work.
> 

That’s nice - how are you trying to run it? Details?

Regarding the X11 variable. I usually log in with ssh -X, which appears to work for me when I run '/opt/rapidminer-studio/RapidMiner-Studio.sh’. You could also try ssh -Y. Keep in mind that if you’re ssh’ing from an ssh connection already, (ssh hopping), then you’ll have to pass the xauth variable for your connection.


> After researching about it, I think that the best solution would be to have the RapidMiner server instead of the RapidMiner-studio client [1]. Would this be possible?
> 
At the time of installation, only the client was requested. Since it requires time on my side to install, and time on the professor’s/assistant’s side to explain to the students, I would need a formal request from the professor or assistant to carry out the RapidMiner Server installation.

> We also wanted to share with you the fact that we switched to MonetDB, that is much faster then postgresql. Therefore, we taught that it would be cool if we could have that on the server so that all of us could use it. Maybe this also helps other teams.
> 

I checked the Debian repos, and there doesn’t appear to be a MonetDB. It appears that they (MonetDB) provide their own Debian/Ubuntu packages. Like I mentioned above, this requires time to install, therefore I would need a formal request.


Cheers,
Tim

**Closed as completed** 2017-01-17 23:24 UTC
